version: '3'
services:
  ts_php:
    build:
      context: ./
      dockerfile: docker/php/Dockerfile-prod
    volumes:
      - .:/var/app:cached
      - ./docker/.env.prod.local:/var/app/.env.local
      - ./docker/php/upload.ini:/usr/local/etc/php/conf.d/upload.ini:ro
    command:
      /bin/bash -c "exec php-fpm"

  ts_nginx:
    image: nginx:latest
    volumes:
      - ./docker/nginx/ts-prod.conf:/etc/nginx/conf.d/ts.conf:ro
      - .:/var/app
    ports:
      - "8080:8080"
    environment:
      - NGINX_HOST=ts.loc
      - NGINX_PORT=8080
      - APP_ENV=dev
    command: /bin/bash -c "exec nginx -g 'daemon off;'"
    depends_on:
      - ts_php
  ts_db:
    image: postgres:9.6
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data:cached
    environment:
      POSTGRES_USER: ts
      POSTGRES_DB: ts
      POSTGRES_PASSWORD: 123456
  ts_socket:
    image: node:latest
    restart: always
    ports:
      - "8081:8081"
    volumes:
    - ./socket-server:/var/app:cached
    command:
      node /var/app/index.js